# See https://sw.kovidgoyal.net/kitty/conf.html
font_family Iosevka Term Nerd Font
font_size 15.000000


active_border_color #b4befe
active_tab_background #1e1e2e
active_tab_foreground #cdd6f4
allow_remote_control no
background #1e1e2e
background_opacity 0.900000
bell_border_color #f38ba8
color0 #45475a
color1 #f38ba8
color10 #a6e3a1
color11 #fab387
color12 #b4befe
color13 #f5c2e7
color14 #89dceb
color15 #cdd6f4
color2 #a6e3a1
color3 #f9e2af
color4 #89b4fa
color5 #cba6f7
color6 #94e2d5
color7 #bac2de
color8 #585b70
color9 #eba0ac
copy_on_select clipboard
cursor #cdd6f4
cursor_beam_thickness 2
cursor_blink_interval 0.600000
cursor_shape beam
cursor_trail 3
cursor_trail_decay 0.1 0.4
cursor_underline_thickness 2
default_pointer_shape beam
detect_urls yes
enable_audio_bell no
foreground #cdd6f4
hide_window_decorations yes
inactive_border_color #313244
inactive_tab_background #313244
inactive_tab_foreground #a6adc8
initial_window_height 30c
initial_window_width 100c
input_delay 1
mouse_hide_wait 3.000000
open_url_with default
paste_actions quote-urls-at-prompt,confirm
pointer_shape_when_dragging beam crosshair
pointer_shape_when_grabbed arrow
remember_window_size yes
repaint_delay 10
resize_debounce_time 0.1 0.5
resize_in_steps no
scrollback_lines 15000
scrollback_pager_history_size 1024
selection_background #313244
selection_foreground #cdd6f4
shell_integration enabled
sync_to_monitor yes
tab_bar_edge top
tab_bar_min_tabs 2
tab_bar_style powerline
tab_title_template {index} {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
touch_scroll_multiplier 10
url_color #89b4fa
url_prefixes file ftp ftps gemini git gopher http https irc ircs kitty mailto news sftp ssh
visual_bell_duration 2.0 ease-in-out
wheel_scroll_min_lines 2
wheel_scroll_multiplier 5
window_alert_on_bell yes
window_border_width 0
window_margin_width 0
window_padding_width 10

env -TERMINFO
env TERMINFO_DIRS terminfo:terminfo:/home/acid/.local/share/.terminfo

