#######################################################################
#                                                                     #
# Ettercap configuration file                                         #
#                                                                     #
#                                                                     #
#######################################################################

[privs]
ec_uid = 65534
ec_gid = 65534

[mitm]
arp_storm_delay = 10
arp_poison_smart = 1
arp_poison_warm_up = 1
arp_poison_delay = 10
arp_poison_equal = 1
dhcp_lease_time = 1800

[connections]
connection_timeout = 120
connection_idle = 300
connection_buffer = 10000
connect_timeout = 5

[stats]
sampling_rate = 50

[misc]
close_on_eof = 0
store_profiles = 1
aggressive_dissectors = 0
skip_forwarded_pcks = 0
checksum_check = 0
checksum_warning = 0
submit_fingerprint = 1
# gateway = ""
# secondary = ""

[curses]
color_bg = 0
color_fg = 7
color_join1 = 6
color_join2 = 6
color_border = 6
color_title = 6
color_focus = 6
color_menu_bg = 4
color_menu_fg = 7
color_window_bg = 4
color_window_fg = 7
color_selection_bg = 6
color_selection_fg = 0
color_error_bg = 1
color_error_fg = 7
color_error_border = 1

[strings]
# redir_command_on = "iptables -t nat -A PREROUTING -i %iface -p tcp --dport %port -j REDIRECT --to-port %rport"
# redir_command_off = "iptables -t nat -D PREROUTING -i %iface -p tcp --dport %port -j REDIRECT --to-port %rport"
remote_browser = "xdg-open http://%host%url"
utf8_encoding = "ISO-8859-1"
