( add balance -0.1
) add balance 0.1
+ add audio-delay -0.05
- add audio-delay +0.05
A cycle angle
C cycle-values video-aspect-override 16:9 4:3 2.35:1 -1
D cycle deinterlace
DOWN add volume -2
E add sub-gauss +0.1
ENTER playlist_next force
F cycle sub-forced-only
I show-text "${media-title}"
LEFT seek -10
PGDWN seek -600
PGUP seek 600
R add sub-gauss -0.1
RIGHT seek 10
Shift+f add sub-scale -0.05
Shift+g add sub-scale +0.05
TAB cycle program
U cycle blend-subtitles
UP add volume 2
WHEEL_DOWN add volume -2
WHEEL_UP add volume 2
Z add sub-delay +0.05
d cycle deband
g sub-reload
l cycle-values sub-ass-override yes  force  no 
n cycle video-unscaled
p cycle sub-fix-timing
u cycle sub-gray
z add sub-delay -0.05