alang="en,eng,de"
audio-file-auto="fuzzy"
audio-pitch-correction=yes
border=no
cscale="ewa_lanczossharp"
cursor-autohide=800
cursor-autohide-fs-only=no
demuxer-max-back-bytes=75000000
demuxer-max-bytes=150000000
demuxer-mkv-subtitle-preroll=yes
dscale="mitchell"
force-seekable="yes"
gpu-api="vulkan"
keepaspect=no
keepaspect-window=no
native-fs=no
osd-bar=no
profile="gpu-hq"
save-position-on-quit=yes
scale="ewa_lanczossharp"
screenshot-directory="~/Pictures/Screenshots"
screenshot-format="png"
screenshot-high-bit-depth=yes
screenshot-png-compression=1
screenshot-template="%f-%wH.%wM.%wS.%wT-#%#00n"
slang="en,eng"
sub-auto="all"
sub-fix-timing=no
term-status-msg="Time: ${time-pos}"
volume=100
volume-max=100
watch-later-directory="~/.cache/mpv/watch-later"
ytdl-format="(bestvideo[height>=4320]/bestvideo[height>=2160]/bestvideo[height>=1440]/bestvideo[height=1080]/bestvideo[height=720])+bestaudio/best"

[1080]
ytdl-format="bestvideo[height<=?1080][fps<=?60][vcodec!=?vp9]+bestaudio/best[height<=?1080]"

[720]
ytdl-format="bestvideo[height<=?720][fps<=?30][vcodec!=?vp9]+bestaudio/best[height<=?720]"

[max]
ytdl-format="bestvideo+bestaudio/best"