alias c='clear'
alias e='exit'
alias se='search'
alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'

alias ls='eza --group-directories-first --icons=auto --color=auto'
alias l='eza -l --group-directories-first --icons=auto --git'
alias la='eza -la --group-directories-first --icons=auto --git'
alias ll='eza -l --group-directories-first --icons=auto --git'
alias lla='eza -lA --group-directories-first --icons=auto --git'
alias lt='eza -l --tree --level=2 --group-directories-first --icons=auto'
alias ltr='eza -l --sort=modified --group-directories-first --icons=auto'
alias lS='eza -l --sort=size --group-directories-first --icons=auto'
alias lsd='eza -l --only-dirs --group-directories-first --icons=auto'
alias l1='eza -1 --group-directories-first --icons=auto'

alias rg='rg --hidden --glob "!**/.direnv/**"'
alias grep='grep --color=auto'
alias grepr='grep -R --color=auto --exclude-dir=.direnv --exclude-dir=.git'
alias bat='bat --paging=never'
alias cat='bat --style=plain --paging=never'
alias fzfb='fzf --preview "bat --color always --style numbers, changes {}"'
alias open='xdg-open'
alias y='yazi'
alias icat='kitty +kitten icat'

alias chmox='chmod +x'
alias temp='cd $(mktemp -d)'
alias po='poweroff'

alias compress='ouch compress'
alias extract='ouch decompress'
