[cmd]
bye = "quit"
c = "buffer clear"
chat = "dcc chat"
close = "buffer close"
exit = "quit"
ig = "ignore"
j = "join"
k = "kick"
kb = "kickban"
leave = "part"
m = "msg"
q = "query"
redraw = "window refresh"
say = "msg *"
signoff = "quit"
t = "topic"
ub = "unban"
umode = "mode $nick"
w = "who"
wc = "window merge"
wi = "whois"
wii = "whois $1 $1"
ww = "whowas"
nullpointer = "/exec -sh -hsignal nullpointer $* 2>&1 | curl -sfSF file=@- https://0x0.st"

[completion]
