[trigger]
nullpointer.enabled = on
nullpointer.hook = hsignal
nullpointer.arguments = "nullpointer"
nullpointer.conditions = ""
nullpointer.regex = "/\n//out"
nullpointer.command = "/command -buffer ${buffer.full_name} core /input delete_line;/command -buffer ${buffer.full_name} core /input insert ${out}"
nullpointer.return_code = ok
nullpointer.post_action = none

weather.enabled = on
weather.hook = command
weather.arguments = "weather"
weather.conditions = ""
weather.regex = "/\s/_/tg_argv_eol1"
weather.command = "/exec -noflush -norc -noln -buffer weather curl -s http://wttr.in/${tg_argv_eol1}?lang=${spell.dict.exec.exec.weather}"
weather.return_code = ok
weather.post_action = none

set_title_weather_buffer.enabled = on
set_title_weather_buffer.hook = print
set_title_weather_buffer.arguments = "exec.exec.weather"
set_title_weather_buffer.conditions = "${tg_message_nocolor} !~ ^\W && ${tg_message_nocolor} !~ (wttr\.in|@igor_chubin)"
set_title_weather_buffer.regex = "/.*$/${tg_message_nocolor}/ /[^:]+:(.*)$/${re:1}/tg_message"
set_title_weather_buffer.command = "/buffer set title ${tg_message_nocolor};/buffer set localvar_set_weather ${tg_message}"
set_title_weather_buffer.return_code = ok
set_title_weather_buffer.post_action = none

setdict.enabled = on
setdict.hook = signal
setdict.arguments = "irc_channel_opened;irc_pv_opened;irc_server_opened"
setdict.conditions = "(${buffer[${tg_signal_data}].full_name} =* *german* || ${buffer[${tg_signal_data}].full_name} =* *deutsch* || ${buffer[${tg_signal_data}].full_name} =* *ger) && ${buffer[${tg_signal_data}].local_variables.type} == channel && ${info:spell_dict,${buffer[${tg_signal_data}].full_name}} !* de,*"
setdict.regex = ""
setdict.command = "/command -buffer ${buffer[${tg_signal_data}].full_name} * /mute /spell setdict de,en"
setdict.return_code = ok
setdict.post_action = none

weather_shortcut.enabled = on
weather_shortcut.hook = modifier
weather_shortcut.arguments = "input_text_for_buffer"
weather_shortcut.conditions = "${buffer[tg_modifier_data].full_name} == exec.exec.weather && ${tg_string_nocolor} !~ ^/"
weather_shortcut.regex = "==(.*)==/weather ${re:1}"
weather_shortcut.command = ""
weather_shortcut.return_code = ok
weather_shortcut.post_action = none
